"""Role model mixin

Revision ID: ec2ab885264a
Revises: 8ac49e12b70e
Create Date: 2023-11-13 10:19:53.907046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'ec2ab885264a'
down_revision: Union[str, None] = '8ac49e12b70e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permission', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('permission', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_permission_id'), 'permission', ['id'], unique=False)
    op.add_column('role', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('role', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_role_id'), 'role', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_role_id'), table_name='role')
    op.drop_column('role', 'updated_at')
    op.drop_column('role', 'created_at')
    op.drop_index(op.f('ix_permission_id'), table_name='permission')
    op.drop_column('permission', 'updated_at')
    op.drop_column('permission', 'created_at')
    # ### end Alembic commands ###
